services:
  # Frontend (React)
  - type: web
    name: fifa-ticket-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://fifa-ticket-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend (Node.js/Express)
  - type: web
    name: fifa-ticket-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: mongodb
    databaseName: sports_tickets
    user: admin